### ISSUE TITLE
3 QS Tiles columns issue

### ISSUE THREAD

**Issue by Kiroolos** [siavash79/AOSPMods#14]
**Describe the bug**
In "Enable 3 QS Tiles columns" option, the second row just showed only the first item. 

**Screenshots**
![Screenshot_20220331-235234.png](https://user-images.githubusercontent.com/43939903/161159852-0cc36b91-15c6-443e-a388-7498ed7a4d51.png)

 - Device: Pixel 6
 - OS: 12.1

**Comment by siavash79** [comment]
QQS tiles, by design, show the first 4 tiles.
We'll have to find a way to patch that...

**Comment by topsy-turvy99** [comment]
> QQS tiles, by design, show the first 4 tiles. We'll have to find a way to patch that...

idk if this will help but here a module that helped me achieving the same result with the help of terminal
https://www.pling.com/p/1582371/

**Comment by siavash79** [comment]
Fixed for next version

**Comment by josephcsible** [comment]
Can you post a link to the commit that fixed this?

**Comment by mingaldrichgan** [comment]
+1 to @josephcsible's request for the commit that fixed this. There is actually still an issue where, in landscape mode, it reverts to 4 tiles per row (which makes sense) but the number of QS tiles showing seems to be hardcoded to 6 regardless of orientation (should be either 4 or 8 to fill 1 or 2 rows in landscape mode).

**Comment by Kiroolos** [comment]
I think it's preferred to be 4 in landscape mode as it still have a bug
Check the below image..

![Screenshot_20220407-231931.png](https://user-images.githubusercontent.com/43939903/162318133-2ed4aba7-4c7a-4670-a551-4b3f7517f9b1.png)

**Comment by Kiroolos** [comment]
@siavash79

**Comment by siavash79** [comment]
@josephcsible 
@mingaldrichgan

**Comment by ElTifo** [comment]
Fixed for next version. Values, on landscape, will rever to default when 3 columns are enabled.

**Comment by EleoXDA** [comment]
Duplicate of:
https://github.com/siavash79/AOSPMods/issues/247
